package com.shieldfraudplugin;

import android.app.Activity;
import android.os.Handler;
import android.os.Looper;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.Callback;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.module.annotations.ReactModule;
import com.facebook.react.modules.core.DeviceEventManagerModule;

import com.shield.android.BlockedDialog;
import com.shield.android.Shield;
import com.shield.android.ShieldCallback;
import com.shield.android.ShieldCrossPlatformHelper;
import com.shield.android.ShieldCrossPlatformParams;
import com.shield.android.ShieldException;

import org.json.JSONObject;

import java.util.HashMap;
import java.util.Map;

/**
 * ShieldFraudPlugin native module — works on both Old and New Architecture.
 *
 * Architecture segmentation on Android is handled by Gradle source sets rather
 * than preprocessor guards (Java has no equivalent of #ifdef). build.gradle
 * selects one of two ShieldFraudPluginSpec shims at compile time:
 *
 *   src/oldarch/ShieldFraudPluginSpec.java
 *     └─ extends ReactContextBaseJavaModule  (Old Architecture / JS bridge)
 *
 *   src/newarch/ShieldFraudPluginSpec.java
 *     └─ extends NativeShieldFraudPluginSpec  (New Architecture / Turbo Module,
 *                                              generated by codegen from
 *                                              src/NativeShieldFraudPlugin.ts)
 *
 * This module always extends ShieldFraudPluginSpec, so the same source file
 * compiles correctly under both architectures.
 *
 * Method-signature notes
 * ──────────────────────
 * • initShield  — logLevel / environmentInfo are declared as `double` because
 *   the JS runtime represents all numbers as 64-bit doubles.  The New Arch
 *   codegen generates `double` for TypeScript `number` params.  The Old Arch
 *   bridge also accepts double — so a single signature covers both.
 *   A `Promise` parameter is included because the TypeScript spec declares
 *   `Promise<void>`; the bridge creates the promise object for Old Arch too.
 *
 * • getSessionId / isShieldInitialized — `@ReactMethod(isBlockingSynchronousMethod = true)`
 *   handles the Old Arch synchronous-bridge path.  New Arch (Turbo Modules)
 *   calls these directly as regular Java methods; the annotation is ignored but
 *   harmless.
 */
@ReactModule(name = ShieldFraudPluginModule.NAME)
public class ShieldFraudPluginModule extends ShieldFraudPluginSpec
        implements ShieldCallback<JSONObject> {

    public static final String NAME = "ShieldFraudPlugin";

    private final ReactApplicationContext reactContext;

    public ShieldFraudPluginModule(ReactApplicationContext reactContext) {
        super(reactContext);
        this.reactContext = reactContext;
    }

    @Override
    @NonNull
    public String getName() {
        return NAME;
    }

    // =========================================================================
    // Synchronous state queries
    //
    // @ReactMethod(isBlockingSynchronousMethod = true) makes the Old Arch bridge
    // return the value synchronously to JS.  Turbo Modules (New Arch) support
    // synchronous returns natively — the annotation is simply ignored there.
    // =========================================================================

    @ReactMethod(isBlockingSynchronousMethod = true)
    public boolean isShieldInitialized() {
        try {
            return Shield.getInstance() != null;
        } catch (IllegalStateException e) {
            return false;
        }
    }

    @ReactMethod(isBlockingSynchronousMethod = true)
    public String getSessionId() {
        return Shield.getInstance().getSessionId();
    }

    // =========================================================================
    // Shield SDK initialisation
    //
    // logLevel / environmentInfo arrive as `double` from both architectures:
    //   • Old Arch — the JS bridge maps JS numbers to double.
    //   • New Arch — the codegen-generated spec declares them as double.
    // They are cast to int internally for the Shield.Builder API.
    //
    // `Promise promise` is required by the TypeScript spec's `Promise<void>`
    // return. The Old Arch bridge creates and wires the promise automatically;
    // New Arch passes it via JSI.
    // =========================================================================

    @ReactMethod
    public void initShield(
            String siteID,
            String secretKey,
            boolean isOptimizedListener,
            @Nullable ReadableMap blockedDialog,
            double logLevel,
            double environmentInfo,
            Promise promise) {

        if (isShieldInitialized()) {
            promise.resolve(null);
            return;
        }

        Activity currentActivity = getCurrentActivity();
        if (currentActivity != null) {
            Shield.Builder builder = new Shield.Builder(currentActivity, siteID, secretKey)
                    .setAutoBlockDialog(getBlockedDialogFromReadableMap(blockedDialog));

            if (isOptimizedListener) {
                builder.registerDeviceShieldCallback(this);
            }

            builder.setEnvironment(getEnvironmentStringFromInt((int) environmentInfo));
            builder.setLogLevel(getLogLevelEnumFromInt((int) logLevel));

            Shield shield = builder.build();
            Shield.setSingletonInstance(shield);
        }

        promise.resolve(null);
    }

    // =========================================================================
    // Shared SDK methods
    //
    // These have identical signatures on both architectures — no segmentation
    // needed. @ReactMethod registers them with the Old Arch bridge; the New
    // Arch codegen dispatcher calls them by the same Java method selector.
    // =========================================================================

    @ReactMethod
    public void setCrossPlatformParameters(String crossPlatformName, String crossPlatformVersion) {
        ShieldCrossPlatformParams params = new ShieldCrossPlatformParams(
                crossPlatformName, crossPlatformVersion);
        ShieldCrossPlatformHelper.setCrossPlatformParameters(params);
    }

    @ReactMethod
    public void setDeviceResultStateListener() {
        new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
            @Override
            public void run() {
                Shield.getInstance().setDeviceResultStateListener(
                        new Shield.DeviceResultStateListener() {
                            @Override
                            public void isReady() {
                                WritableMap params = Arguments.createMap();
                                params.putString("status", "isSDKReady");
                                reactContext
                                        .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                                        .emit("device_result_state", params);
                            }
                        });
            }
        }, 1500);
    }

    @ReactMethod
    public void sendAttributes(String screenName, ReadableMap json) {
        HashMap<String, String> data = new HashMap<>();
        for (Map.Entry<String, Object> entry : json.toHashMap().entrySet()) {
            data.put(entry.getKey(), (String) entry.getValue());
        }
        Shield.getInstance().sendAttributes(screenName, data);
    }

    @ReactMethod
    public void getLatestDeviceResult(Callback successCallback, Callback errorCallback) {
        Shield shieldInstance = Shield.getInstance();
        JSONObject deviceResult = shieldInstance.getLatestDeviceResult();

        if (deviceResult != null) {
            successCallback.invoke(deviceResult.toString());
        } else {
            ShieldException error = shieldInstance.getResponseError();
            String errorMessage = (error != null) ? error.getMessage() : "unknown error";
            errorCallback.invoke(errorMessage);
        }
    }

    // Required stubs for RCTEventEmitter compatibility on both architectures
    @ReactMethod
    public void addListener(String eventName) {}

    @ReactMethod
    public void removeListeners(double count) {}

    // =========================================================================
    // ShieldCallback delegate — forwarded as JS events
    // =========================================================================

    @Override
    public void onSuccess(@Nullable JSONObject jsonObject) {
        if (jsonObject != null) {
            reactContext
                    .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                    .emit("success", jsonObject.toString());
        }
    }

    @Override
    public void onFailure(@Nullable ShieldException e) {
        if (e != null) {
            reactContext
                    .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                    .emit("error", e.getLocalizedMessage());
        }
    }

    // =========================================================================
    // Internal helpers
    // =========================================================================

    @Nullable
    private BlockedDialog getBlockedDialogFromReadableMap(@Nullable ReadableMap blockedDialog) {
        if (blockedDialog != null) {
            String title = blockedDialog.hasKey("title") ? blockedDialog.getString("title") : null;
            String body  = blockedDialog.hasKey("body")  ? blockedDialog.getString("body")  : null;
            return new BlockedDialog(title, body);
        }
        return null;
    }

    private String getEnvironmentStringFromInt(int environment) {
        switch (environment) {
            case 1:  return Shield.ENVIRONMENT_DEV;
            case 2:  return Shield.ENVIRONMENT_STAGING;
            default: return Shield.ENVIRONMENT_PROD;
        }
    }

    private Shield.LogLevel getLogLevelEnumFromInt(int logLevel) {
        switch (logLevel) {
            case 1:  return Shield.LogLevel.NONE;
            case 2:  return Shield.LogLevel.INFO;
            case 3:  return Shield.LogLevel.DEBUG;
            default: return Shield.LogLevel.VERBOSE;
        }
    }
}
