package com.shieldfraudplugin;

import com.facebook.react.bridge.ReactApplicationContext;

/**
 * New Architecture base class for ShieldFraudPluginModule.
 *
 * Selected by Gradle when newArchEnabled=true.
 * Extends NativeShieldFraudPluginSpec — the abstract class generated by React
 * Native's codegen from the TypeScript spec at src/NativeShieldFraudPlugin.ts.
 *
 * How the source-set swap works
 * ─────────────────────────────
 * build.gradle adds either src/oldarch or src/newarch to the Java source
 * directories depending on the newArchEnabled project property:
 *
 *   sourceSets {
 *     main {
 *       if (isNewArchitectureEnabled()) {
 *         java.srcDirs += ['src/newarch']   // this file is included
 *       } else {
 *         java.srcDirs += ['src/oldarch']   // this file is excluded
 *       }
 *     }
 *   }
 *
 * ShieldFraudPluginModule (in src/main/) always extends ShieldFraudPluginSpec,
 * so it compiles correctly regardless of which shim is selected.
 *
 * NativeShieldFraudPluginSpec is generated at build time by the React Native
 * Gradle plugin (com.facebook.react) when New Architecture is enabled.
 * It declares all methods from the TypeScript spec as abstract — this shim
 * exists purely to bridge the inheritance chain so ShieldFraudPluginModule
 * does not need to import the codegen class directly.
 */
abstract class ShieldFraudPluginSpec extends NativeShieldFraudPluginSpec {

    protected ShieldFraudPluginSpec(ReactApplicationContext context) {
        super(context);
    }
}
